### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by blankhart** [utkarshkukreti/purescript-hedwig#10]
It would be great if you could clarify the intended license terms for Hedwig.

The same question also applies to Hertz actually - I used Hertz as a reference in an experiment notwithstanding that the repo is archived, but will remove the example if there is any objection to its use there (https://github.com/blankhart/purescript-servant-routing).

**Comment by utkarshkukreti** [comment]
Hi. Consider both the projects MIT licensed. If you need any other license in addition to MIT, let me know!

**Comment by blankhart** [comment]
Thanks!
